services:
  libkttsserver:
    image: ghcr.io/yanorei32/libktts-server:v0.1.3
    hostname: libkttsserver
    container_name: libkttsserver${VARIANT:-}__libkttsserver

    restart: unless-stopped

    environment:
      MAXIMUM_LENGTH: ${MAXIMUM_LENGTH:-512}

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.6.0
    hostname: cloudflared
    container_name: libkttsserver${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 4096m

    networks:
      default:

networks:
  default:
    name: libkttsserver${VARIANT:-}__default
